import type { Metadata } from 'next';
import './globals.css';
// import ClientLayout from './client-layout'; // Import your client-side wrapper
import Script from 'next/script';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

import { ClerkProvider } from '@clerk/nextjs';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider>
      <html>
        <head>
          <Script
            src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"
            strategy="afterInteractive"
          />
        </head>
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}

//
